// <auto-generated />
namespace ERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class b5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(b5));
        
        string IMigrationMetadata.Id
        {
            get { return "201711010549172_b5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
